myblog/comments/urls.py
from django.conf.urls import url
from . import views
app_name = 'comments'
urlpatterns = [
        url(r'^comment/article/(?P<article_id>[0-9]+)/$',views.article_comment,name='article_comment'),
        ]

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as main_views
from django.conf.urls.static import static
from django.conf import settings
from messageboard import views as messageboard_views
import django.views.static
from myblog.settings import BASE_DIR
import os
from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^blog/photolist/$',main_views.photoGroup,name='photoGroup'),
    url(r'^blog/search/$',main_views.search,name='search'),
    url(r'^blog/lifelist/$',main_views.LifeList.as_view(),name='lifelist'),
    url(r'^blog/codelist/$',main_views.CodeView.as_view(),name='codelist'),
    url(r'^blog/detail/(?P<id>[0-9]+)/$',main_views.detail,name='detail'),
    url(r'^blog/ckt/admin/', admin.site.urls),
    url(r'^blog/$',main_views.indexView.as_view(),name='index'),
    url(r'^blog/ueditor/',include('DjangoUeditor.urls' )),
    url(r'blog/',include('comments.urls')),
    url(r'^blog/messageboard/$',messageboard_views.Messageboard,name='message'),
    url(r'blog/static/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static')}),
    url(r'^blog/accounts/', include('users.urls')),
    ]

myblog/comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
	"""docstring for Comment"""
	name = models.CharField(max_length=20)
	email = models.EmailField(max_length=30)
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True)
	article = models.ForeignKey('blog.Article')

	def __str__(self):
		return self.text[:20]
		

myblog/main/models.py
from django.db import models

# Create your models here.

myblog/main/views.py
from django.shortcuts import render,get_object_or_404,redirect
from comments.forms import CommentForm
import json
from blog.models import Article
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
import markdown2
from django.views.generic import ListView
from django.db.models import Q
from django.http import HttpResponseRedirect  
# Create your views here.

def search(request):
	q = request.GET.get('q')
	error_msg = ''
	if not q:
		error_msg = "请输入关键词"
		return render(request,'search.html',{'error_msg':error_msg})
	search_list = Article.objects.filter(Q(title__icontains=q) | Q(content__icontains=q))
	context = {'search_list':search_list,'error_msg':error_msg}
	goodview_list = Article.objects.all().order_by('-views')
	goodview_list = goodview_list[:6]
	context.update({'goodview_list':goodview_list})
	return render(request,'search.html',context=context)


def detail(request,id):
	article = Article.objects.get(id=id)
	article.increase_views()
	form = CommentForm()
	comment_list = article.comment_set.all().order_by('-created_time')
	context = {'article':article,'form':form,'comment_list':comment_list}
	goodview_list = Article.objects.all().order_by('-views')
	goodview_list = goodview_list[:6]
	context.update({'goodview_list':goodview_list})
	return render(request,'detail.html',context=context)

class LifeList(ListView):
	model = Article
	template_name = 'life_list.html'
	context_object_name = 'life_list'
	paginate_by = 5
	def get_queryset(self):		
		life_list = Article.objects.filter(article_cate='life').order_by('-update_time')
		return life_list

	def get_context_data(self, **kwargs):

		context = super().get_context_data(**kwargs)
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')
		pagination_data = self.pagination_data(paginator, page, is_paginated)
		context.update(pagination_data)
		goodview_list = Article.objects.all().order_by('-views')
		goodview_list = goodview_list[:6]
		context.update({'goodview_list':goodview_list})
		return context

	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:
			return {}

		left = []
		right = []
		left_has_more = False
		right_has_more = False
		first = False
		last = False
		page_number = page.number
		total_pages = paginator.num_pages
		page_range = paginator.page_range

		if page_number == 1:
			right = page_range[page_number:page_number + 2]
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

		elif page_number == total_pages:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
			 	first = True
		else:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			right = page_range[page_number:page_number + 2]

			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
			'left': left,
			'right': right,
			'left_has_more': left_has_more,
			'right_has_more': right_has_more,
			'first': first,
			'last': last,
        }

		return data

		

class CodeView(ListView):
	model = Article
	template_name = 'code_list.html'
	context_object_name = 'code_list'
	paginate_by = 5
	def get_queryset(self):		
		code_list = Article.objects.filter(article_cate='code').order_by('-update_time')
		return code_list
	def get_context_data(self, **kwargs):

		context = super().get_context_data(**kwargs)
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')
		pagination_data = self.pagination_data(paginator, page, is_paginated)
		context.update(pagination_data)
		goodview_list = Article.objects.all().order_by('-views')
		goodview_list = goodview_list[:6]
		context.update({'goodview_list':goodview_list})
		return context

	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:
			return {}

		left = []
		right = []
		left_has_more = False
		right_has_more = False
		first = False
		last = False
		page_number = page.number
		total_pages = paginator.num_pages
		page_range = paginator.page_range

		if page_number == 1:
			right = page_range[page_number:page_number + 2]
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

		elif page_number == total_pages:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
			 	first = True
		else:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			right = page_range[page_number:page_number + 2]

			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
			'left': left,
			'right': right,
			'left_has_more': left_has_more,
			'right_has_more': right_has_more,
			'first': first,
			'last': last,
        }

		return data


class indexView(ListView):
	model = Article
	template_name = 'basemain.html'
	context_object_name = 'blog_list'
	paginate_by = 5
	def get_queryset(self):
		blog_list = Article.objects.all().order_by('-update_time')
		return blog_list

	def get_context_data(self, **kwargs):

		context = super().get_context_data(**kwargs)
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')
		pagination_data = self.pagination_data(paginator, page, is_paginated)
		context.update(pagination_data)
		goodview_list = Article.objects.all().order_by('-views')
		goodview_list = goodview_list[:6]
		context.update({'goodview_list':goodview_list})
		return context

	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:
			return {}

		left = []
		right = []
		left_has_more = False
		right_has_more = False
		first = False
		last = False
		page_number = page.number
		total_pages = paginator.num_pages
		page_range = paginator.page_range

		if page_number == 1:
			right = page_range[page_number:page_number + 2]
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

		elif page_number == total_pages:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
			 	first = True
		else:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			right = page_range[page_number:page_number + 2]

			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
			'left': left,
			'right': right,
			'left_has_more': left_has_more,
			'right_has_more': right_has_more,
			'first': first,
			'last': last,
        }

		return data

def photoGroup(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/')
	else:
		return redirect('/')

myblog/main/templates/accounts_profile.html
{% extends 'basemain.html' %}

{% block title %}个人信息修改{% endblock %}

{% block content %}

<h2>信息完善</h2>

<div id="app">
	<table class="table table-hover form-group">
		<thead>
			<tr>
				<th>编号</th>
				<th>项目</th>
				<th>值</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>0</td>
				<td>账户（不可改)</td>
				<td><span v-text="email" class="form-control">#</span></td>
				<tr>
					<td>1</td>
					<td>姓名</td>
					<td><input v-model="name" class="form-control"></td>
				</tr>
				<tr>
					<td>2</td>
					<td>性别</td>
					<td><select v-model='sex' class="form-control">
						<option value="男">男</option>
						<option value="女">女</option>
					</select></td>
				</tr>
				<tr><td>3</td>
					<td>生日</td>
					<td>
					<input type="date" v-model="birthday" class="form-control"></td>
				</tr>
				<tr>
					<td>4</td>
					<td>电话</td>
					<td><input v-model="phone" class="form-control"></td>
				</tr>
				<tr>
					<td>5</td>
					<td>工作</td>
					<td><input v-model="job" class="form-control"></td>
				</tr>
		</tbody>
	</table>
<button @click="submit" class="btn btn-primary">保存</button>
{% endblock %}

{% block vuejs %}
<script type="text/javascript">
var vm = new Vue({
	el: '#app',
	data:{
		email: '{{ request.user.email}}',
		name: '{{request.user.name}}',
		sex: '{{request.user.sex}}',
		birthday: '{{request.user.birthday}}',
		phone: '{{request.user.phone}}',
		job: '{{request.user.job}}',
	},
	methods:{
		submit(){
			data_to_send = {
				name: this.name,
				sex: this.sex,
				birthday: this.birthday,
				phone: this.phone,
				job: this.job,
			};
			console.log(data_to_send);
			data_to_send = JSON.stringify(data_to_send);
			console.log(data_to_send);

			$.post('/accounts/profile/',
				data_to_send,
				function(r,err){
					if(err === 'success'){
						alert('保存成功！')
						return location.assign('/');
					}else{
						return console.log(err);
					}
				});
		},
	},
});
</script>
{% endblock %}

myblog/main/templates/basemain.html
<!DOCTYPE html>
<html >
<head>
	{% load staticfiles %}
	<!--bootstrap-->
	<link href="/blog/static/css/bootstrap.css" rel="stylesheet">
	<link  href="/blog/static/css/font-awesome.min.css" rel="stylesheet">
	<link href="/blog/static/css/bootstrap-theme.css" rel="stylesheet">
	<script src="/blog/static/js/jquery.js"></script>
	<script src="/blog/static/js/bootstrap.js"></script>
    <!--vue-->
	<script src="/blog/static/js/vue.js"></script>
	<!--csrf token-->
	<script type="text/javascript" src="/blog/static/js/csrf.js"></script>
	<script type="text/javascript" charset="utf-8" src="/blog/static/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/blog/static/ueditor/ueditor.all.min.js"> </script>
    <script type="text/javascript" charset="utf-8" src="/blog/static/ueditor/lang/zh-cn/zh-cn.js"></script>
    <title>{% block title %}My Blog{% endblock %}</title>
</head>

		
<body>
	<nav class="navbar" role="navgation">
	<div id="nav" class="navbar-fixed-top navbar-default">
		<a href="/blog/">
		<div class="navbar-brand" style="font-size: 30px;font-family:Brush Script MT;">
			Alex Blog
		</div>
	</a>
		<div>
		<ul class="nav navbar-nav" style="margin-left: 100px; font-size: 18px;">
			<li><a href="/blog/">首页</a></li>
			<li><a href="/blog/codelist">学无止境</a></li>
			<li><a href="/blog/lifelist">生活点滴</a></li>
			<li><a href="/blog/messageboard">留言板</a></li>
			<li><a href="/blog/photolist">相册</a></li>
			</ul>
	</div>
	
		<form role="search" method="get" id="searchform" action="/blog/search">
			<div  class="col-lg-2" style="margin-top: 7px;margin-left:200px;">
		<div class="input-group">
		<input type="search" class="form-control" name="q" placeholder="搜索" required>
		<span class="input-group-btn">
			<button class="btn btn-default" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
		</span>

		</div>
		</div>
	</form>
		

	
</div>
</nav>
	<div class="container">
		<div class=" col-md-9 ">
		{% block content %}
			{% for article in page_obj %}
			
			{% include 'blog_list.html' %}
			
			{% endfor %}
			{% include 'pagination.html' %}	
		{% endblock %}
	</div>
	<div class="col-md-3 panel panel-default">

		<div style="text-align: center;" class="panle-title">
			<br><br>
		<img src="/blog/static/img/boy_20180222151606_397.jpg" class="img-circle" style="width: 80px;height: 80px;">
		<br><br>
		<p style="font-size: 25px;font-family:Bradley Hand;"><strong>Alex Chen</strong></p>
		</div>

		
		<div >
			
			<ul>
				<p style="font-size: 18px;">热门文章</p>
				{% for article in goodview_list %}
				<li><a style="color: black;" href="/blog/{{article.get_absolute_url}}">{{ article.title }}</a></li>
				{% endfor %}
			</ul>
			
			
		</div>
	</div>
	</div>
	<footer class="panel-footer">
		<div class="container text-center ">

		<p style="font-size: 14px;"> Powered by <b> Alex Chen</b>
		<br> Copyright 2018<a href="mailto:330953853@qq.com">联系我</a></p>
	</div>
	</footer>
	

	{% block vuejs %}
 	{% endblock %}
 	{% if errors %}
 	<script>
 		alert('{{errors}}')
 	</script>
 	{% endif %}
</body>
</html>

myblog/main/templates/blog_list.html
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><a style="color: black" href="{{article.get_absolute_url}}" >{{ article.title}}</a></h4>
	</div>
	<div class="panel-body">
		<dl>
				<dd><p><a style="font-size: 14px;color:black;" href="{{article.get_absolute_url}}">{{article.abstract}}.......</a>
				
				</p></dd>
			</dl>
	</div>
	<div class="panel-footer">
		<div style="text-align: right;"> <i class="fa fa-eye" aria-hidden="true"></i> {{article.views}}&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-clock-o" aria-hidden="true"></i> {{article.update_time|date:"Y-m-d"}}</div>
	</div>
</div>

				

myblog/main/templates/code_list.html
{% extends 'basemain.html' %}
{% block title %}Alex Blog Code{% endblock %}
{% block content %}
{% for article in page_obj %}
			
			{% include 'blog_list.html' %}
			
			{% endfor %}
			{% include 'pagination.html' %}	
 {% endblock %}

myblog/main/templates/detail.html
{% extends 'basemain.html' %}
{% block content %}
<div style="text-align: center;"><h2>{{article.title}}</h2>
<br>
<div style="text-align: right;">时间：{{article.update_time|date:"Y-m-d H:i:s"}}</div>
</div>
<br><br>
<div><p style="font-size: 20px">{{article.content|safe}}</p></div>
<form action="{% url 'comments:article_comment' article.id %}" class="bs-example bs-example-form" method="post">
	{% csrf_token %}
	<div class="well">
    <p><strong>发表评论</strong></p>
    <div class="input-group">
      <span class="input-group-addon">姓名</span>
      <input type="text" name="name" placeholder="请填写你的姓名" style="width: 200px" class="form-control" maxlength="20" required id="id_name" />
      
      {{ form.name.errors }}
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon">邮箱</span>
      <input type="email" placeholder="请填写你的邮箱" name="email" style="width: 200px" class="form-control" maxlength="30" required id="id_email" />
      {{ form.email.errors }}
    </div>
    <br>
    <div class="input-group">
      评论：
      <br>
      <textarea name="text" cols="90" placeholder="发表你的看法" rows="6" style="resize: none;" required id="id_text">
</textarea>
      {{ form.text.errors }}
      <br>
      <button type="submit" class="btn btn-primary">发表</button>
    </div>
  </div> 
</form>
<p><strong>评论列表</strong></p>
<ul class="list-group">
  {% for comment in comment_list %}
  <li class="list-group-item">
    <span><strong style="font-size:18px;font-family:sans-serif;">{{ comment.name }} · </strong></span>
    <time class="submit-date">{{ comment.created_time|date:"Y-m-d H:i:s" }}</time>
    <div class="text">
      <br>
     <p style="font-size: 16px;font-family:lucida grande,Hiragino Sans GB;"> {{ comment.text }}</p>
    </div>
  </li>
  {% empty %}
  <p><strong>暂无评论</strong></p>
  {% endfor %}
</ul>
{% endblock %}

myblog/main/templates/life_list.html
{% extends 'basemain.html' %}
{% block title %}Alex Blog Life{% endblock %}
{% block content %}
{% for article in page_obj %}
			
			{% include 'blog_list.html' %}
			
			{% endfor %}
			{% include 'pagination.html' %}	
 {% endblock %}

myblog/main/templates/pagination.html
<nav aria-lable="Page navgation">
	<ul class="pagination">
		{% if is_paginated %}
  {% if first %}
   <li> <a href="?page=1">1</a></li>
  {% endif %}
  {% if left %}
    {% if left_has_more %}
     <li><span>...</span></li>
    {% endif %}
    {% for i in left %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endfor %}
  {% endif %}
 <li class="active"> <a href="?page={{ page_obj.number }}" >{{ page_obj.number }}</a></li>
  {% if right %}
    {% for i in right %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endfor %}
    {% if right_has_more %}
        <li><span>...</span></li>
    {% endif %}
  {% endif %}
  {% if last %}
    <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
  {% endif %}
  {% endif %}
</ul>
</nav>

myblog/main/templates/search.html
{% extends 'basemain.html' %}
{% block title %}搜索{% endblock %}
{% block content %}
{% if error_msg %}
<p>{{ error_msg }}</p>
{% endif %}
{% for article in search_list %}
{% include 'blog_list.html' %}
{% empty %}
<div class="container">
	抱歉，没有找到您想要的文章！！
</div>
{% endfor %}
{% endblock %}